services:
  bot:
    build: .
    network_mode: host
    env_file:
      - .env
  redis:
    image: redis:8-alpine
    container_name: weather_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis-data:
    driver: local
